**TASK:** import numpy

In [2]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [27]:
x=np.array([1,2,3])
x

array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [28]:
A=np.eye(2)
A

array([[1., 0.],
       [0., 1.]])

**TASK:** define (2 x 2) matrix 'B'

In [29]:
B=np.eye(2)
B

array([[1., 0.],
       [0., 1.]])

**TASK:** check the type of 'x'

In [30]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [31]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [32]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [33]:
A.shape

(2, 2)

**TASK:** 

In [34]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [35]:
def have_same_shape (array_1,array_2):
    return(array_1.shape==array_2.shape)
        

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [36]:
have_same_shape(x,A)

False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [37]:
have_same_shape(B,A)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [41]:
def matrix_addition(array_1,array_2):
    return(array_1+array_2)

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [44]:
matrix_addition(A,B)

array([[2., 0.],
       [0., 2.]])

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [45]:
def multiple_matrix_adition (list):
    return(np.array(list))

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [48]:
C=multiple_matrix_adition([A,A,B,B,B])
C.shape
C

array([[[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [49]:
def can_multiply(array_a,array_b):
    return(array_a.shape[-1]==array_b.shape[0])

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [50]:
can_multiply(A,B)

True

**TASK:**  define matrix (3 x 2) matrix C

In [58]:
C=np.array([[1,2],[4,5],[7,8]])
C.shape

(3, 2)

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [59]:
can_multiply(A,C)

False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [60]:
can_multiply(C,A)

True

In [ ]:
yes. the number of columns of the first matrix should be equal to the number of the rows in the seccond matrix. so being the 1st or 2nd one in matrix multiply matters.

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [79]:
def matrix_multiplication(array_a,array_b):
    M=np.zeros((array_a.shape[0],array_b.shape[1]))
    M
    if(can_multiply(array_a,array_b)):
        for i in range(array_a.shape[0]):
            for j in range(array_b.shape[1]):
                for k in range(array_a.shape[1]):
                    M[i][j]+=array_a[i][k]*array_b[k][j]
        return(M)
    else:
        return('cannot multiply!')

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [80]:
matrix_multiplication(C,B)

array([[1., 2.],
       [4., 5.],
       [7., 8.]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [81]:
matrix_multiplication(A,C)

'cannot multiply!'