# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
a[4] = 1
a



array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
b = np.arange(10, 50)
bb[::-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [7]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [12]:
c = np.array([1,2,0,0,4,0])
np.where(c>0)
# or using .nonzero function(method), either
c.nonzero()
# or this way
np.nonzero(c)

(array([0, 1, 4]),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.rand(3,3,3)

array([[[0.57276484, 0.1735769 , 0.8829634 ],
        [0.21569141, 0.9712118 , 0.76902609],
        [0.44241851, 0.36062261, 0.17040736]],

       [[0.15859907, 0.61874036, 0.4281537 ],
        [0.41592164, 0.65322815, 0.75859666],
        [0.99104004, 0.58441985, 0.23083145]],

       [[0.25459911, 0.99182173, 0.02158421],
        [0.75814316, 0.96181853, 0.82277617],
        [0.58985044, 0.05414832, 0.09039918]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
d = np.random.rand(10, 10)
print(d)



d.min()
d.max()

[[0.40567935 0.27040196 0.59276995 0.80591231 0.63057998 0.07626158
  0.8825597  0.15684722 0.79624256 0.07000121]
 [0.54605486 0.94597942 0.88403975 0.78321244 0.57219551 0.79468867
  0.35748883 0.2167504  0.01822084 0.95125699]
 [0.37831555 0.18776894 0.65285033 0.5282332  0.89206877 0.28571174
  0.22768019 0.55958615 0.85485733 0.7376321 ]
 [0.53371759 0.21860536 0.42146825 0.84556476 0.97149998 0.82325198
  0.02418908 0.99344596 0.34327001 0.96336568]
 [0.09235015 0.43145235 0.66077817 0.83878911 0.65490026 0.74432077
  0.53261602 0.26196668 0.52585012 0.24460045]
 [0.18342488 0.61116481 0.17221318 0.86108003 0.94832481 0.96038153
  0.76241255 0.83657267 0.95616954 0.72913013]
 [0.76740559 0.84567945 0.13470324 0.03961987 0.23829296 0.17017633
  0.15113137 0.14360249 0.89513785 0.50352893]
 [0.8842651  0.34417393 0.78809525 0.06813295 0.72698848 0.34960926
  0.57114191 0.87412591 0.87740426 0.34783699]
 [0.40265658 0.29231825 0.6142323  0.65731139 0.25574957 0.15769563
  0.25074314

0.9934459610994869

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
e = np.random.randint(10, size=30)
e

array([0, 6, 7, 6, 0, 4, 7, 0, 6, 3, 4, 9, 9, 2, 9, 8, 5, 8, 7, 7, 7, 8,
       9, 2, 4, 2, 3, 7, 3, 0])

In [18]:
e.mean()

5.066666666666666

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
f = np.ones((5,5))
f[1:-1, 1:-1] = 0
print(f)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
a, b = f.shape[0]+2, f.shape[1]+2
g = np.zeros((a, b))
g[1:-1, 1:-1] = f
print(g)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [22]:
a, b = f.shape[0]+2, f.shape[1]+2
g = np.zeros((a, b))
g[1:-1, 1:-1] = f
print(g)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan                   nan
np.nan == np.nan             False
np.inf > np.nan              False
np.nan - np.nan              nan
np.nan in set([np.nan])      True
0.3 == 3 * 0.1               False
```

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
h = np.identity(5)
rng = np.arange(1,5)
h[rng, rng-1] = rng
h

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

In [24]:
# Or use the k parameter in .diag function
np.diag(np.arange(4)+1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [25]:
# or one can use .eye to create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [26]:
# each x has 56 elements, with 44 left     -> x = 1
# each row has 8 unit: 44/8 = 5.5, it lands on 6th row, with 4 left  -> y = 5
# with 4 left, so it lands on 4th column        -> z = 3
arr = np.arange(1, 337).reshape((6,7,8))
arr[1, 5, 3]

100

In [27]:
# Or use .unravel_index function
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [28]:
arr1 = np.arange(25).reshape(5,5)

In [29]:
(arr1 - np.mean(arr1)) / np.std(arr1)

array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
       [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
       [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
       [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
       [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])

#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [33]:
ar2 = np.random.randint(15, size=10)
ar2

array([ 8, 12,  4, 11,  6,  5, 10,  7,  8,  3])

In [34]:
# where() returns a tuple
ind = np.where((ar2>3) & (ar2<8))[0]

In [35]:
ar2[ind] *= -1

In [36]:
ar2

array([ 8, 12, -4, 11, -6, -5, 10, -7,  8,  3])

In [37]:
# or a simpler way
arr3 = np.random.randint(15, size=10)
arr3[(arr3>3) & (arr3<8)] *= -1
arr3

array([ 8,  0, 12, 11, -4,  8, -4,  9,  8,  8])

#### 18. How to round away from zero a float array ? (★☆☆)

In [38]:
arr4 = np.random.normal(0,10,10)
arr4

array([-0.05640308, -6.63363842,  9.30156177,  2.68762914, -0.30690804,
        6.5300252 , -0.49077587, -5.86376136,  8.4680435 , 21.85645188])

In [39]:
# use .abs, .ceil, and .copysign functions
np.copysign(np.ceil(np.abs(arr4)), arr4)

array([-1., -7., 10.,  3., -1.,  7., -1., -6.,  9., 22.])

#### 19. Find common values between two arrays? (★☆☆)

In [40]:
a = np.array([1,2,3,4,5,6,7,8,2])
b = np.array([2,10,7,20])
np.intersect1d(a, b)

array([2, 7])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [41]:
np.sqrt(-1)

<ipython-input-41-597592b72a04>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [48]:
np.emath.sqrt(-1)

1j

In [49]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-49-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [50]:
# a generator function
def give_10_int():
    n = 10    
    while n > 0:
        yield np.random.randint(10)
        n -= 1

In [51]:
arr = []
for el in give_10_int():
    arr.append(el)
arr = np.array(arr)

In [52]:
arr

array([5, 5, 2, 4, 4, 6, 5, 4, 5, 6])

In [53]:
# or use .fromiter(iterable, dtype) function to create an array
Z = np.fromiter(give_10_int(), dtype='int32')
print(Z)

[9 7 4 1 8 4 2 8 2 2]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [54]:
# use .linspace function
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [55]:
# sort the array ascendingly
np.sort(np.random.random(10))

array([0.04441974, 0.0926916 , 0.09960127, 0.39943475, 0.42805699,
       0.47417638, 0.55457288, 0.79845173, 0.8855183 , 0.98823587])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [56]:
A = np.random.random(size=10)
B = np.random.random(size=10)
A

array([0.42107979, 0.22565514, 0.99925882, 0.49270901, 0.24171509,
       0.08473374, 0.814016  , 0.13426579, 0.13823396, 0.47377189])

In [57]:
B

array([0.15907111, 0.03224532, 0.19743324, 0.08603677, 0.30535481,
       0.68839021, 0.91437524, 0.56503592, 0.21429839, 0.26743185])

In [58]:
# does not allow tolerance
np.array_equal(A, B)

False

In [59]:
# allows little tolerance: 1e-08
# np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
# Returns True if two arrays are element-wise equal within a tolerance.

np.allclose(A, B)

False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [60]:
arr = np.random.randint(10, size=10)
arr

array([7, 7, 5, 5, 9, 6, 3, 3, 7, 1])

In [61]:
# only replace the first max value
arr[np.argmax(arr)] = 0
arr

array([7, 7, 5, 5, 0, 6, 3, 3, 7, 1])

#### 26. Find the closest value to random element in a vector? (★★☆)

In [63]:
arr1 = np.random.randint(10, size=10)
arr2 = np.arange(10)
arr1

array([7, 8, 3, 5, 1, 8, 6, 3, 9, 0])

In [64]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.abs(arr1 - arr2)

array([7, 7, 1, 2, 3, 3, 0, 4, 1, 9])

In [67]:
arr1[(np.abs(arr1 - arr2)).argmin()]

6

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [62]:
a = np.array([1.3,2.6,3,1.0,4.94,5], dtype='float32')
a

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [70]:
# use .astype() method
a = a.astype('int32', copy=False)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 2], dtype=int32)

In [71]:
# use .view() method
y = a.view(np.int32)
y[:] = a
y

array([1, 2, 3, 4, 5, 6, 7, 8, 2], dtype=int32)

#### 28. Sort an array by the nth column? (★★☆)

In [72]:
x = np.random.randint(25, size=25).reshape(5,5)
x

array([[ 9, 16,  0,  6,  4],
       [19, 22,  0,  5,  3],
       [12, 10, 10,  7,  3],
       [17, 19, 11, 14, 10],
       [21,  9, 13, 23, 14]])

In [73]:
# example: Sort by n=0 column
n = 0
x[x[:, n].argsort()]

array([[ 9, 16,  0,  6,  4],
       [12, 10, 10,  7,  3],
       [17, 19, 11, 14, 10],
       [19, 22,  0,  5,  3],
       [21,  9, 13, 23, 14]])

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [74]:
x = np.random.randint(25, size=25).reshape(5,5)
x[:, 2] = 0
x

array([[ 2, 24,  0,  3,  9],
       [16, 22,  0,  5, 11],
       [ 4,  1,  0, 21, 21],
       [ 8, 17,  0, 17,  3],
       [ 8, 21,  0,  5,  5]])

In [75]:
# use .all()
(np.all(x==0, axis=0)).any()

True

In [76]:
# or use .any() method, better way
(~x.any(axis=0)).any()

True

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [77]:
y = np.array([1,2,3,4,5], dtype='int8')
zeros = 3

In [78]:
x = np.zeros(len(y) + (len(y)-1)*zeros, dtype='int8')
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [79]:
x[::zeros+1] = y
print(x)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 31. Swap two rows of an array? (★★★)

In [80]:
x = np.random.randint(25, size=25).reshape(5,5)
x

array([[11,  4, 15, 14,  0],
       [15, 10, 13,  7,  8],
       [12,  5, 18, 24, 18],
       [11,  8,  6, 20, 23],
       [18, 20, 20, 14, 23]])

In [81]:
# swap row 1 and 2
x[[0,1]] = x[[1,0]]
x

array([[15, 10, 13,  7,  8],
       [11,  4, 15, 14,  0],
       [12,  5, 18, 24, 18],
       [11,  8,  6, 20, 23],
       [18, 20, 20, 14, 23]])

#### 32. How to negate a boolean value inside an array? (★★★)

In [82]:
a = np.random.uniform(-5, 5, 10)
b = np.random.randint(0,2,10)
a

array([ 3.54914428, -0.33873314,  4.40079468,  4.61444454, -0.0976983 ,
       -0.46130071,  0.6806863 ,  1.32837212, -1.1255024 , -1.21535754])

In [83]:
# a Boolean array
b

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 1])

In [84]:
# Compute the truth value of NOT x element-wise
np.logical_not(b, out=b)

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0])

In [85]:
# negate float numbers
np.negative(a, out=a)

array([-3.54914428,  0.33873314, -4.40079468, -4.61444454,  0.0976983 ,
        0.46130071, -0.6806863 , -1.32837212,  1.1255024 ,  1.21535754])

#### 33. Find the most frequent value in an array?

In [90]:
z = np.random.randint(1, 25, size=20)
z

array([21, 19, 10, 21,  6,  8,  3, 15,  3, 24,  3, 16,  1,  1, 23,  1, 14,
        1, 22,  5])

In [91]:
# find the first most frequent value
y = np.bincount(z).argmax()
y

1

In [93]:
## find the all most frequent values
#maximum = max(y)
#for i in range(len(y)):
#    if y[i] == maximum:
#        print(i, end=" ")

#### 34. Get the n largest values of an array (★★★)

In [94]:
arr = np.random.randint(2, 15, size=7)
np.random.shuffle(arr)
n = 3
arr

array([ 9, 13,  7, 11, 10,  8, 14])

In [95]:
# this works but slow
arr[np.argsort(arr)][-n:]

array([11, 13, 14])

In [96]:
np.sort(arr)

array([ 7,  8,  9, 10, 11, 13, 14])

In [97]:
# use .argpartion() and its more efficient
np.argpartition(arr, n)

array([2, 5, 0, 4, 3, 1, 6])

In [98]:
# retrieve last n largest values
arr[np.argpartition(arr, n)][-n:]

array([11, 13, 14])

#### 35. Extract unique rows from a two dimensional array? (★★★)

In [99]:
r = np.array([[1,2,3,4,5], [5,4,3,2,1], [2,3,4,5,6], [1,2,3,4,5], [3,4,5,6,7], [2,3,4,5,6]])
r

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6]])

In [100]:
# extract rows without duplicates
arr, cnt = np.unique(r, axis=0, return_counts=True)
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [5, 4, 3, 2, 1]])

In [101]:
# exact ONLY unique in the array
arr[cnt == 1]

array([[3, 4, 5, 6, 7],
       [5, 4, 3, 2, 1]])